version: '3.8'
services:
  redis:
    container_name: redis-core
    image: redis:7.2.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - c:/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - core-network-sg

networks:
  core-network-sg:
    name: core-network-s-gob
    driver: bridge