export type LevelSyslogType = 'INFO' | 'WARN' | 'ERROR' | 'DEBUG' | 'NOTE' | 'CONNECT' | 'DISCONNECT' | 'RECONNECTING' | 'NONE';
export type SourceSyslogType =
  | 'GRAL'
  | 'APPLICATION'
  | 'APPLICATION_SERVICES'
  | 'APPLICATION_VALIDATIONS'
  | 'DOMAIN'
  | 'DOMAIN_DTOS'
  | 'DOMAIN_ENTITIES'
  | 'DOMAIN_MAPPERS'
  | 'DOMAIN_PORTS'
  | 'INFRASTRUCTURE'
  | 'INFRASTRUCTURE_ADAPTER'
  | 'INFRASTRUCTURE_ADAPTER_REPOSITORY'
  | 'INFRASTRUCTURE_ADAPTER_SERVICE'
  | 'INFRASTRUCTURE_CONTROLLERS'
  | 'INFRASTRUCTURE_RESOLVERS'
  | 'INFRASTRUCTURE_QUEUE'
  | 'DATA_BASE';
